apiVersion: apps/v1
kind: Deployment
metadata:
  name: diagnoai
  namespace: diagnoai
  labels:
    app: diagnoai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diagnoai
  template:
    metadata:
      labels:
        app: diagnoai
    spec:
      containers:
      - name: diagnoai
        image: bhupencod3/diagnoai:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: diagnoai-config
        env:
        - name: GROK_API_KEY
          valueFrom:
            secretKeyRef:
              name: diagnoai-secrets
              key: grok-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5
        volumeMounts:
        - name: vector-store-volume
          mountPath: /app/data/vector_store
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: vector-store-volume
        persistentVolumeClaim:
          claimName: vector-store-pvc
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc