apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: diagnoai-hpa
  namespace: diagnoai
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: diagnoai
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70